In [1]:
!nvidia-smi

Tue Apr 11 10:17:15 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 528.02       Driver Version: 528.02       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   51C    P0    16W /  60W |      0MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import cv2 as cv

In [3]:
import os
HOME = os.getcwd()
print(HOME)

C:\Users\user\PycharmProjects\computer_vision_faster\Related


In [4]:
#!pip install ultralytics

In [5]:
from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

Ultralytics YOLOv8.0.66  Python-3.10.8 torch-1.13.1+cu116 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
Setup complete  (12 CPUs, 15.7 GB RAM, 374.3/476.2 GB disk)


In [6]:
# Метод для установки из репозитория

# Git clone method (for development)

# %cd {HOME}
# !git clone github.com/ultralytics/ultralytics
# %cd {HOME}/ultralytics
# !pip install -qe ultralytics

# from IPython import display
# display.clear_output()

# import ultralytics
# ultralytics.checks()

In [7]:
from ultralytics import YOLO

from IPython.display import display, Image

In [8]:
model = YOLO('yolov8n.pt')

In [ ]:
model.train()

In [9]:
im2 = cv.imread('000000000650.jpg')
results = model.predict(source=im2, save=True, save_txt=True)


0: 448x640 1 car, 1 cat, 15.0ms
Speed: 1.0ms preprocess, 15.0ms inference, 5.0ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs\detect\predict5
1 label saved to runs\detect\predict5\labels


In [10]:
results

[ultralytics.yolo.engine.results.Results object with attributes:
 
 _keys: ('boxes', 'masks', 'probs', 'keypoints')
 boxes: ultralytics.yolo.engine.results.Boxes object
 keypoints: None
 keys: ['boxes']
 masks: None
 names: {0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 5

In [11]:
model.export(format='onnx', opset=12)

Ultralytics YOLOv8.0.66  Python-3.10.8 torch-1.13.1+cu116 CPU

PyTorch: starting from yolov8n.pt with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)

ONNX: starting export with onnx 1.13.1 opset 12...
ONNX: export success  0.8s, saved as yolov8n.onnx (12.2 MB)

Export complete (1.0s)
Results saved to C:\Users\user\PycharmProjects\computer_vision_faster\Related
Predict:         yolo predict task=detect model=yolov8n.onnx imgsz=640 
Validate:        yolo val task=detect model=yolov8n.onnx imgsz=640 data=coco.yaml 
Visualize:       https://netron.app


'yolov8n.onnx'

In [1]:
from onnxruntime import InferenceSession

In [2]:
providers = ['CPUExecutionProvider']
session = InferenceSession('yolov8n.onnx', providers=providers)


In [3]:
from PIL import Image
import numpy as np

# Load the image and convert it to a numpy array
image_path = "000000000650.jpg"
image = Image.open(image_path)
image_array = np.array(image)
image_array = image_array.astype(np.float32)
print(image_array.shape)
image_array.resize((640, 640, 3))
print(image_array)
image_array = np.transpose(image_array, (2, 0, 1))
print(image_array.shape)
image_array = np.expand_dims(image_array, axis=0)
print(image_array.shape)

(427, 640, 3)
[[[255. 250. 228.]
  [255. 251. 229.]
  [255. 252. 231.]
  ...
  [ 77.  80.  51.]
  [ 79.  82.  53.]
  [ 80.  83.  54.]]

 [[250. 242. 219.]
  [252. 244. 221.]
  [255. 246. 224.]
  ...
  [ 76.  79.  50.]
  [ 77.  80.  51.]
  [ 78.  81.  52.]]

 [[253. 241. 215.]
  [255. 244. 218.]
  [255. 246. 220.]
  ...
  [ 75.  78.  49.]
  [ 76.  79.  52.]
  [ 77.  80.  53.]]

 ...

 [[  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  ...
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]]

 [[  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  ...
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]]

 [[  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  ...
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]]]
(3, 640, 640)
(1, 3, 640, 640)


In [4]:
# Run the input data through the model
input_name = session.get_inputs()[0].name
output_name = session.get_outputs()[0].name
result = session.run(None, {input_name: image_array})

In [12]:
print(result)
print(type(result))
print(result[0][0][0][0])
print(result[0][0][0][1])
print(result[0][0][0][2])
print(result[0][0][0][3])
print(result[0][0][0][4])
print(result[0][0][0][5])
print(result[0][0][0][6])
print(result[0][0][0][7])
print(result[0][0][0][8])
print(result[0][0][0][9])

[array([[[4.9832554e+00, 1.1378820e+01, 2.8395935e+01, ...,
         5.0330273e+02, 5.4728076e+02, 5.8909479e+02],
        [3.9741526e+00, 4.0922203e+00, 7.9543896e+00, ...,
         5.8250330e+02, 5.7145154e+02, 5.4380139e+02],
        [1.4032261e+01, 1.4491901e+01, 3.1305147e+01, ...,
         2.7735815e+02, 1.8817267e+02, 1.0568396e+02],
        ...,
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         1.3113022e-06, 9.2387199e-07, 2.8312206e-06],
        [2.0861626e-07, 2.9802322e-08, 5.9604645e-08, ...,
         1.1026859e-06, 1.0132790e-06, 1.3411045e-06],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         1.5497208e-06, 1.4007092e-06, 1.9967556e-06]]], dtype=float32)]
<class 'list'>
4.9832554
11.37882
28.395935
33.03505
32.66423
41.577564
52.068768
61.69626
67.61752
78.37096
